apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:41a56e3077fe03831130a5915e68ecd23eeb0f61f99396769b7f5a50c32e9e6b
  name: quay.io/bluesman/vote-ui:latest
  newName: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/pipelines-vote-ui
